import os
import time
from db import get_db_connection
from datetime import datetime

def format_row(row, cursor):
    return {cursor.description[i][0]: value for i, value in enumerate(row)}

def migrate_economic_groups():
    conn = get_db_connection()
    try:
        with conn.cursor() as cursor:
            print("Creating economic_groups table...")
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.economic_groups (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    master_group_id BIGINT NOT NULL,
                    name STRING NOT NULL,
                    sector STRING,
                    rating STRING,
                    created_at TIMESTAMP
                )
            """)

            print("Adding economic_group_id to operations...")
            cursor.execute("DESCRIBE cri_cra_dev.crm.operations")
            op_cols_all = [row.col_name for row in cursor.fetchall()]
            if 'economic_group_id' not in op_cols_all:
                cursor.execute("ALTER TABLE cri_cra_dev.crm.operations ADD COLUMN economic_group_id BIGINT")
                
            print("Adding rating_master_group to rating_history...")
            cursor.execute("DESCRIBE cri_cra_dev.crm.rating_history")
            rh_cols_all = [row.col_name for row in cursor.fetchall()]
            if 'rating_master_group' not in rh_cols_all:
                cursor.execute("ALTER TABLE cri_cra_dev.crm.rating_history ADD COLUMN rating_master_group STRING")
            
            # Create a generic economic group for each master group
            print("Retrieving existing master groups to create generic economic groups...")
            cursor.execute("SELECT id, name, sector, rating FROM cri_cra_dev.crm.master_groups")
            mgs = cursor.fetchall()
            
            for mg in mgs:
                mg_id = mg.id
                mg_name = mg.name
                # Check if a generic economic group already exists for this master group
                cursor.execute("SELECT id FROM cri_cra_dev.crm.economic_groups WHERE master_group_id = ? AND name = ?", (mg_id, mg_name))
                existing_eg = cursor.fetchone()
                
                if existing_eg:
                    eg_id = existing_eg.id
                else:
                    print(f"Creating economic group '{mg_name}' for master group {mg_id}...")
                    cursor.execute("""
                        INSERT INTO cri_cra_dev.crm.economic_groups (master_group_id, name, sector, rating, created_at)
                        VALUES (?, ?, ?, ?, ?)
                    """, (mg_id, mg_name, mg.sector, mg.rating, datetime.now()))
                    
                    cursor.execute("SELECT id FROM cri_cra_dev.crm.economic_groups WHERE master_group_id = ? ORDER BY id DESC LIMIT 1", (mg_id,))
                    eg_id = cursor.fetchone().id
                
                # Update operations that belong to this master_group to point to the new economic_group
                print(f"Updating operations for master group {mg_id} -> economic group {eg_id}...")
                cursor.execute("UPDATE cri_cra_dev.crm.operations SET economic_group_id = ? WHERE master_group_id = ? AND (economic_group_id IS NULL)", (eg_id, mg_id))
            
            # Updating contacts table
            print("Renaming master_group_contacts to operation_contacts and adding operation_id...")
            cursor.execute("SHOW TABLES IN cri_cra_dev.crm")
            tables = [row.tableName for row in cursor.fetchall()]
            
            if 'operation_contacts' not in tables and 'master_group_contacts' in tables:
                cursor.execute("ALTER TABLE cri_cra_dev.crm.master_group_contacts RENAME TO cri_cra_dev.crm.operation_contacts")
            
            if 'operation_contacts' in tables or 'master_group_contacts' in tables:
                target_table = 'operation_contacts' if 'operation_contacts' in tables else 'master_group_contacts'
                cursor.execute(f"DESCRIBE cri_cra_dev.crm.{target_table}")
                contact_cols_all = [row.col_name for row in cursor.fetchall()]
                
                if 'operation_id' not in contact_cols_all:
                    cursor.execute(f"ALTER TABLE cri_cra_dev.crm.{target_table} ADD COLUMN operation_id BIGINT")
                    
                # To maintain existing contacts in UI, link them to the FIRST operation of that master group
                cursor.execute(f"SELECT id, master_group_id FROM cri_cra_dev.crm.{target_table} WHERE operation_id IS NULL AND master_group_id IS NOT NULL")
                unlinked_contacts = cursor.fetchall()
                for contact in unlinked_contacts:
                    cursor.execute("SELECT id FROM cri_cra_dev.crm.operations WHERE master_group_id = ? LIMIT 1", (contact.master_group_id,))
                    op = cursor.fetchone()
                    if op:
                        cursor.execute(f"UPDATE cri_cra_dev.crm.{target_table} SET operation_id = ? WHERE id = ?", (op.id, contact.id))

            print("Migration completed successfully!")
            conn.commit()

    except Exception as e:
        print(f"Migration failed: {e}")
        import traceback
        traceback.print_exc()
    finally:
        conn.close()

if __name__ == "__main__":
    migrate_economic_groups()
