import os
import json
from datetime import datetime
from db import get_db_connection

def format_row(row, cursor):
    return {cursor.description[i][0]: value for i, value in enumerate(row)}

def update_schema():
    conn = get_db_connection()
    try:
        with conn.cursor() as cursor:
            print("Ensuring master_groups table exists...")
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.master_groups (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name STRING NOT NULL,
                    sector STRING,
                    rating STRING
                )
            """)
            
            print("Ensuring master_group_contacts table exists...")
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.master_group_contacts (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    master_group_id BIGINT NOT NULL,
                    name STRING NOT NULL,
                    email STRING,
                    phone STRING,
                    role STRING
                )
            """)
            
            # --- MIGRATE FROM structuring_operations IF EXISTS ---
            print("Checking operations table existence before migration...")
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.operations (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name STRING NOT NULL,
                    area STRING,
                    operation_type STRING,
                    maturity_date TIMESTAMP,
                    responsible_analyst STRING,
                    review_frequency STRING,
                    call_frequency STRING,
                    df_frequency STRING,
                    segmento STRING,
                    rating_operation STRING,
                    rating_group STRING,
                    watchlist STRING,
                    ltv FLOAT,
                    dscr FLOAT,
                    monitoring_news BOOLEAN,
                    monitoring_fii_report BOOLEAN,
                    monitoring_operational_info BOOLEAN,
                    monitoring_receivables_portfolio BOOLEAN,
                    monitoring_construction_report BOOLEAN,
                    monitoring_commercial_info BOOLEAN,
                    monitoring_spe_dfs BOOLEAN,
                    status STRING,
                    description STRING,
                    moved_to_legacy_date TIMESTAMP,
                    master_group_id BIGINT,
                    is_structuring BOOLEAN,
                    pipeline_stage STRING,
                    rate STRING,
                    indexer STRING,
                    volume FLOAT,
                    fund STRING,
                    risk STRING,
                    temperature STRING,
                    liquidation_date TIMESTAMP,
                    is_active BOOLEAN
                )
            """)

            print("Checking for structuring fields in operations...")
            cursor.execute("DESCRIBE cri_cra_dev.crm.operations")
            op_cols_all = [row.col_name for row in cursor.fetchall()]
            new_cols = {
                'is_structuring': 'BOOLEAN',
                'pipeline_stage': 'STRING',
                'rate': 'STRING',
                'indexer': 'STRING',
                'volume': 'FLOAT',
                'fund': 'STRING',
                'risk': 'STRING',
                'temperature': 'STRING',
                'liquidation_date': 'TIMESTAMP',
                'is_active': 'BOOLEAN',
                'originator': 'STRING',
                'modality': 'STRING'
            }
            for col, dtype in new_cols.items():
                if col not in op_cols_all:
                    cursor.execute(f"ALTER TABLE cri_cra_dev.crm.operations ADD COLUMN {col} {dtype}")
            
            if 'is_structuring' not in op_cols_all:
                cursor.execute("UPDATE cri_cra_dev.crm.operations SET is_structuring = FALSE, is_active = TRUE WHERE is_structuring IS NULL")
            if 'status' not in op_cols_all:
                cursor.execute("ALTER TABLE cri_cra_dev.crm.operations ADD COLUMN status STRING")
            if 'description' not in op_cols_all:
                cursor.execute("ALTER TABLE cri_cra_dev.crm.operations ADD COLUMN description STRING")
            if 'moved_to_legacy_date' not in op_cols_all:
                cursor.execute("ALTER TABLE cri_cra_dev.crm.operations ADD COLUMN moved_to_legacy_date TIMESTAMP")
            if 'master_group_id' not in op_cols_all:
                cursor.execute("ALTER TABLE cri_cra_dev.crm.operations ADD COLUMN master_group_id BIGINT")
                
            nullable_cols = ['operation_type', 'maturity_date', 'responsible_analyst', 'review_frequency', 'call_frequency', 'df_frequency', 'rating_operation', 'rating_group', 'watchlist']
            for col in nullable_cols:
                try:
                    cursor.execute(f"ALTER TABLE cri_cra_dev.crm.operations ALTER COLUMN {col} DROP NOT NULL")
                except Exception: pass
            
            # Data Migration
            try:
                cursor.execute("SELECT * FROM cri_cra_dev.crm.structuring_operations")
                struct_ops = cursor.fetchall()
                old_to_new_op_id = {}
                for row in struct_ops:
                    op = format_row(row, cursor)
                    cursor.execute("SELECT id FROM cri_cra_dev.crm.operations WHERE name = ? AND master_group_id = ? AND is_structuring = TRUE", (op['name'], op.get('master_group_id')))
                    existing = cursor.fetchone()
                    if existing:
                        old_to_new_op_id[op['id']] = existing.id
                        continue
                    
                    cursor.execute("""
                        INSERT INTO cri_cra_dev.crm.operations (
                            name, area, master_group_id, pipeline_stage, liquidation_date, 
                            rate, indexer, volume, fund, responsible_analyst, 
                            risk, temperature, is_active, is_structuring
                        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, TRUE)
                    """, (
                        op['name'], 'CRI', op.get('master_group_id'), op.get('stage'), op.get('liquidation_date'),
                        op.get('rate'), op.get('indexer'), op.get('volume'), op.get('fund'), op.get('analyst'),
                        op.get('risk'), op.get('temperature'), op.get('is_active', True)
                    ))
                    
                    cursor.execute("SELECT id FROM cri_cra_dev.crm.operations WHERE name = ? AND is_structuring = TRUE ORDER BY id DESC LIMIT 1", (op['name'],))
                    new_op_id = cursor.fetchone().id
                    old_to_new_op_id[op['id']] = new_op_id
                    
                    try: cursor.execute("UPDATE cri_cra_dev.crm.structuring_operation_series SET structuring_operation_id = ? WHERE structuring_operation_id = ?", (new_op_id, op['id']))
                    except Exception: pass
                    try: cursor.execute("UPDATE cri_cra_dev.crm.structuring_operation_stages SET structuring_operation_id = ? WHERE structuring_operation_id = ?", (new_op_id, op['id']))
                    except Exception: pass
            except Exception as e:
                print("Skipping structuring_operations migration:", e)

            # Table Renames
            try:
                cursor.execute("ALTER TABLE cri_cra_dev.crm.structuring_operation_series RENAME TO cri_cra_dev.crm.operation_series")
                cursor.execute("ALTER TABLE cri_cra_dev.crm.operation_series RENAME COLUMN structuring_operation_id TO operation_id")
            except Exception: pass
            try:
                cursor.execute("ALTER TABLE cri_cra_dev.crm.structuring_operation_stages RENAME TO cri_cra_dev.crm.operation_stages")
                cursor.execute("ALTER TABLE cri_cra_dev.crm.operation_stages RENAME COLUMN structuring_operation_id TO operation_id")
            except Exception: pass

            try: cursor.execute("ALTER TABLE cri_cra_dev.crm.events RENAME COLUMN structuring_operation_stage_id TO operation_stage_id")
            except Exception: pass
            try: cursor.execute("ALTER TABLE cri_cra_dev.crm.task_rules RENAME COLUMN structuring_operation_stage_id TO operation_stage_id")
            except Exception: pass

            try: cursor.execute("DROP TABLE IF EXISTS cri_cra_dev.crm.structuring_operations")
            except Exception: pass

            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.operation_series (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    operation_id BIGINT NOT NULL,
                    name STRING NOT NULL,
                    rate STRING,
                    indexer STRING,
                    volume FLOAT,
                    fund STRING,
                    FOREIGN KEY (operation_id) REFERENCES cri_cra_dev.crm.operations(id)
                )
            """)

            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.operation_stages (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    operation_id BIGINT NOT NULL,
                    name STRING NOT NULL,
                    order_index INT NOT NULL,
                    is_completed BOOLEAN
                )
            """)

            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.projects (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name STRING NOT NULL,
                    status STRING,
                    state STRING,
                    city STRING
                )
            """)
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.guarantees (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name STRING NOT NULL,
                    type STRING,
                    value FLOAT,
                    description STRING
                )
            """)
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.operation_projects (
                    operation_id BIGINT NOT NULL,
                    project_id BIGINT NOT NULL,
                    PRIMARY KEY (operation_id, project_id)
                )
            """)
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.operation_guarantees (
                    operation_id BIGINT NOT NULL,
                    guarantee_id BIGINT NOT NULL,
                    PRIMARY KEY (operation_id, guarantee_id)
                )
            """)

            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.rating_history (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    operation_id BIGINT,
                    master_group_id BIGINT,
                    date TIMESTAMP NOT NULL,
                    rating_operation STRING NOT NULL,
                    rating_group STRING NOT NULL,
                    watchlist STRING,
                    sentiment STRING,
                    event_id BIGINT
                )
            """)

            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.events (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    operation_id BIGINT,
                    master_group_id BIGINT,
                    date TIMESTAMP NOT NULL,
                    type STRING NOT NULL,
                    title STRING NOT NULL,
                    description STRING NOT NULL,
                    registered_by STRING NOT NULL,
                    next_steps STRING,
                    completed_task_id STRING,
                    attention_points STRING,
                    our_attendees STRING,
                    operation_attendees STRING,
                    is_origination BOOLEAN,
                    operation_stage_id BIGINT
                )
            """)

            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.task_rules (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    operation_id BIGINT,
                    name STRING NOT NULL,
                    frequency STRING NOT NULL,
                    start_date TIMESTAMP,
                    end_date TIMESTAMP,
                    description STRING,
                    priority STRING,
                    is_origination BOOLEAN,
                    operation_stage_id BIGINT
                )
            """)

            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.operation_review_notes (
                    operation_id BIGINT PRIMARY KEY,
                    notes STRING,
                    updated_at TIMESTAMP NOT NULL,
                    updated_by STRING NOT NULL
                )
            """)
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.task_exceptions (
                    task_id STRING PRIMARY KEY,
                    operation_id BIGINT,
                    deleted_at TIMESTAMP,
                    deleted_by STRING
                )
            """)
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.audit_logs (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    timestamp TIMESTAMP NOT NULL,
                    user_name STRING NOT NULL,
                    action STRING NOT NULL,
                    entity_type STRING NOT NULL,
                    entity_id STRING NOT NULL,
                    details STRING
                )
            """)
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.change_requests (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    title STRING NOT NULL,
                    description STRING NOT NULL,
                    requester STRING NOT NULL,
                    status STRING NOT NULL,
                    created_at TIMESTAMP NOT NULL,
                    updated_at TIMESTAMP NOT NULL
                )
            """)
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.patch_notes (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    version STRING NOT NULL,
                    date TIMESTAMP NOT NULL,
                    title STRING NOT NULL,
                    description STRING NOT NULL,
                    changes STRING NOT NULL
                )
            """)
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.sync_queue (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    operation_id BIGINT NOT NULL,
                    data STRING NOT NULL,
                    created_at TIMESTAMP,
                    processed BOOLEAN
                )
            """)
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.analyst_notes (
                    analyst_name STRING PRIMARY KEY,
                    notes STRING,
                    updated_at TIMESTAMP NOT NULL
                )
            """)
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.operation_risks (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    operation_id BIGINT,
                    master_group_id BIGINT,
                    title STRING NOT NULL,
                    description STRING,
                    severity STRING,
                    created_at TIMESTAMP,
                    updated_at TIMESTAMP
                )
            """)
            
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cri_cra_dev.crm.fund_allocation_inputs (
                    fund_name STRING PRIMARY KEY,
                    emission FLOAT DEFAULT 0.0,
                    prepayment FLOAT DEFAULT 0.0,
                    repurchases FLOAT DEFAULT 0.0,
                    new_repo FLOAT DEFAULT 0.0,
                    updated_at TIMESTAMP
                )
            """)

            # Seed Patch notes
            cursor.execute("SELECT COUNT(*) as count FROM cri_cra_dev.crm.patch_notes")
            if cursor.fetchone().count == 0:
                print("Adding initial patch notes...")
                initial_changes = json.dumps(["Implementação inicial", "Gestão de operações unificada"])
                cursor.execute("""
                    INSERT INTO cri_cra_dev.crm.patch_notes (version, date, title, description, changes)
                    VALUES (?, ?, ?, ?, ?)
                """, ("1.0.0", datetime.now(), "Lançamento Inicial", "Primeira versão estável do sistema CRM.", initial_changes))

            conn.commit()
    except Exception as e:
        print(f"Error updating schema: {e}")
    finally:
        conn.close()

if __name__ == "__main__":
    update_schema()
