import os
import json
import re
from datetime import datetime
from db import get_db_connection

# Define all tables and their columns
SCHEMA = {
    "cri_cra_dev.crm.master_groups": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "name STRING NOT NULL",
        "sector STRING",
        "rating STRING"
    ],
    "cri_cra_dev.crm.economic_groups": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "master_group_id BIGINT NOT NULL",
        "name STRING NOT NULL",
        "sector STRING",
        "rating STRING",
        "created_at TIMESTAMP"
    ],
    "cri_cra_dev.crm.master_group_contacts": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "master_group_id BIGINT NOT NULL",
        "name STRING NOT NULL",
        "email STRING",
        "phone STRING",
        "role STRING"
    ],
    "cri_cra_dev.crm.operations": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "name STRING NOT NULL",
        "area STRING",
        "operation_type STRING",
        "maturity_date TIMESTAMP",
        "responsible_analyst STRING",
        "structuring_analyst STRING",
        "review_frequency STRING",
        "call_frequency STRING",
        "df_frequency STRING",
        "segmento STRING",
        "rating_operation STRING",
        "watchlist STRING",
        "ltv FLOAT",
        "dscr FLOAT",
        "monitoring_news BOOLEAN",
        "monitoring_fii_report BOOLEAN",
        "monitoring_operational_info BOOLEAN",
        "monitoring_receivables_portfolio BOOLEAN",
        "monitoring_construction_report BOOLEAN",
        "monitoring_commercial_info BOOLEAN",
        "monitoring_spe_dfs BOOLEAN",
        "status STRING",
        "description STRING",
        "moved_to_legacy_date TIMESTAMP",
        "master_group_id BIGINT",
        "economic_group_id BIGINT",
        "is_structuring BOOLEAN",
        "pipeline_stage STRING",
        "rate STRING",
        "indexer STRING",
        "volume FLOAT",
        "fund STRING",
        "risk STRING",
        "temperature STRING",
        "liquidation_date TIMESTAMP",
        "estimated_date TIMESTAMP",
        "is_active BOOLEAN",
        "originator STRING",
        "modality STRING",
        "created_at TIMESTAMP",
        "was_structured BOOLEAN"
    ],
    "cri_cra_dev.crm.operation_series": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "operation_id BIGINT NOT NULL",
        "name STRING NOT NULL",
        "rate STRING",
        "indexer STRING",
        "volume FLOAT",
        "fund STRING",
        "FOREIGN KEY (operation_id) REFERENCES cri_cra_dev.crm.operations(id)"
    ],
    "cri_cra_dev.crm.operation_stages": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "operation_id BIGINT NOT NULL",
        "name STRING NOT NULL",
        "order_index INT NOT NULL",
        "is_completed BOOLEAN"
    ],
    "cri_cra_dev.crm.projects": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "name STRING NOT NULL",
        "status STRING",
        "state STRING",
        "city STRING"
    ],
    "cri_cra_dev.crm.guarantees": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "name STRING NOT NULL",
        "type STRING",
        "value FLOAT",
        "description STRING"
    ],
    "cri_cra_dev.crm.operation_projects": [
        "operation_id BIGINT NOT NULL",
        "project_id BIGINT NOT NULL",
        "PRIMARY KEY (operation_id, project_id)"
    ],
    "cri_cra_dev.crm.operation_guarantees": [
        "operation_id BIGINT NOT NULL",
        "guarantee_id BIGINT NOT NULL",
        "PRIMARY KEY (operation_id, guarantee_id)"
    ],
    "cri_cra_dev.crm.operation_contacts": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "operation_id BIGINT NOT NULL",
        "name STRING NOT NULL",
        "email STRING",
        "phone STRING",
        "role STRING"
    ],
    "cri_cra_dev.crm.rating_history": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "operation_id BIGINT",
        "master_group_id BIGINT",
        "date TIMESTAMP NOT NULL",
        "rating_operation STRING NOT NULL",
        "rating_group STRING NOT NULL",
        "watchlist STRING",
        "sentiment STRING",
        "event_id BIGINT"
    ],
    "cri_cra_dev.crm.operation_litigation_comments": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "operation_id BIGINT",
        "date TIMESTAMP NOT NULL",
        "description STRING",
        "user_name STRING"
    ],
    "cri_cra_dev.crm.events": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "operation_id BIGINT",
        "master_group_id BIGINT",
        "date TIMESTAMP NOT NULL",
        "type STRING NOT NULL",
        "title STRING NOT NULL",
        "description STRING NOT NULL",
        "registered_by STRING NOT NULL",
        "next_steps STRING",
        "completed_task_id STRING",
        "attention_points STRING",
        "our_attendees STRING",
        "operation_attendees STRING",
        "is_origination BOOLEAN",
        "operation_stage_id BIGINT"
    ],
    "cri_cra_dev.crm.task_rules": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "operation_id BIGINT",
        "name STRING NOT NULL",
        "frequency STRING NOT NULL",
        "start_date TIMESTAMP",
        "end_date TIMESTAMP",
        "description STRING",
        "priority STRING",
        "is_origination BOOLEAN",
        "operation_stage_id BIGINT"
    ],
    "cri_cra_dev.crm.operation_review_notes": [
        "operation_id BIGINT PRIMARY KEY",
        "notes STRING",
        "updated_at TIMESTAMP NOT NULL",
        "updated_by STRING NOT NULL"
    ],
    "cri_cra_dev.crm.task_exceptions": [
        "task_id STRING PRIMARY KEY",
        "operation_id BIGINT",
        "deleted_at TIMESTAMP",
        "deleted_by STRING"
    ],
    "cri_cra_dev.crm.audit_logs": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "timestamp TIMESTAMP NOT NULL",
        "user_name STRING NOT NULL",
        "action STRING NOT NULL",
        "entity_type STRING NOT NULL",
        "entity_id STRING NOT NULL",
        "details STRING"
    ],
    "cri_cra_dev.crm.change_requests": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "title STRING NOT NULL",
        "description STRING NOT NULL",
        "requester STRING NOT NULL",
        "status STRING NOT NULL",
        "created_at TIMESTAMP NOT NULL",
        "updated_at TIMESTAMP NOT NULL"
    ],
    "cri_cra_dev.crm.patch_notes": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "version STRING NOT NULL",
        "date TIMESTAMP NOT NULL",
        "title STRING NOT NULL",
        "description STRING NOT NULL",
        "changes STRING NOT NULL"
    ],
    "cri_cra_dev.crm.sync_queue": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "operation_id BIGINT NOT NULL",
        "data STRING NOT NULL",
        "created_at TIMESTAMP",
        "processed BOOLEAN"
    ],
    "cri_cra_dev.crm.analyst_notes": [
        "analyst_name STRING PRIMARY KEY",
        "notes STRING",
        "updated_at TIMESTAMP NOT NULL"
    ],
    "cri_cra_dev.crm.operation_risks": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "operation_id BIGINT",
        "master_group_id BIGINT",
        "title STRING NOT NULL",
        "description STRING",
        "severity STRING",
        "created_at TIMESTAMP",
        "updated_at TIMESTAMP"
    ],
    "cri_cra_dev.crm.fund_allocation_inputs": [
        "fund_name STRING PRIMARY KEY",
        "emission FLOAT",
        "prepayment FLOAT",
        "repurchases FLOAT",
        "new_repo FLOAT",
        "simulated_ops_overrides STRING",
        "updated_at TIMESTAMP"
    ]
}

# ──────────────────────────────────────────────────────────────
# Schema: cri_cra_dev.comite  (Comitê de Investimento / Monitoramento)
# ──────────────────────────────────────────────────────────────
COMITE_SCHEMA = {
    "cri_cra_dev.comite.comite_rules": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "tipo STRING NOT NULL",           # investimento | monitoramento
        "area STRING",
        "dia_da_semana STRING",
        "horario STRING",
        "data_criacao TIMESTAMP",
        "ativo BOOLEAN"
    ],
    "cri_cra_dev.comite.comites": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "comite_rule_id BIGINT NOT NULL",
        "data TIMESTAMP NOT NULL",
        "status STRING NOT NULL",          # agendado | concluido
        "ata_gerada_em TIMESTAMP"
    ],
    "cri_cra_dev.comite.comite_secoes": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "comite_id BIGINT NOT NULL",
        "nome STRING NOT NULL",
        "ordem INT NOT NULL",
        "is_default BOOLEAN"
    ],
    "cri_cra_dev.comite.comite_itens_pauta": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "comite_id BIGINT NOT NULL",
        "secao_id BIGINT",
        "titulo STRING NOT NULL",
        "descricao STRING",
        "criador_user_id BIGINT",
        "criador_nome STRING",
        "tipo STRING",                     # video | presencial
        "video_url STRING",
        "video_duracao STRING",
        "prioridade STRING",               # normal | alta | urgente
        "operation_id BIGINT",             # FK nullable → crm.operations ou structuring
        "tipo_caso STRING",                # aprovacao | revisao | geral
        "created_at TIMESTAMP"
    ],
    "cri_cra_dev.comite.comite_comentarios": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "item_pauta_id BIGINT NOT NULL",
        "user_id BIGINT",
        "user_nome STRING",
        "texto STRING NOT NULL",
        "parent_comment_id BIGINT",        # FK p/ threading (respostas)
        "created_at TIMESTAMP"
    ],
    "cri_cra_dev.comite.comite_likes": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "comentario_id BIGINT NOT NULL",
        "user_id BIGINT NOT NULL",
        "created_at TIMESTAMP"
    ],
    "cri_cra_dev.comite.comite_votos": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "item_pauta_id BIGINT NOT NULL",
        "user_id BIGINT NOT NULL",
        "user_nome STRING",
        "tipo_voto STRING NOT NULL",       # aprovado | reprovado | discussao
        "cargo_voto STRING",               # gestao | risco | diretoria
        "comentario STRING",
        "created_at TIMESTAMP",
        "updated_at TIMESTAMP"
    ],
    "cri_cra_dev.comite.comite_videos_assistidos": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "item_pauta_id BIGINT NOT NULL",
        "user_id BIGINT NOT NULL",
        "user_nome STRING",
        "assistido BOOLEAN",
        "created_at TIMESTAMP"
    ],
    "cri_cra_dev.comite.comite_proximos_passos": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "item_pauta_id BIGINT",
        "comite_id BIGINT",
        "descricao STRING NOT NULL",
        "responsavel_user_id BIGINT",
        "responsavel_nome STRING",
        "status STRING",                   # pendente | concluido
        "created_at TIMESTAMP"
    ],
    "cri_cra_dev.comite.comite_config_email": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "comite_rule_id BIGINT NOT NULL",
        "horario_envio STRING",
        "habilitado BOOLEAN"
    ],
    "cri_cra_dev.comite.users": [
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        "nome STRING NOT NULL",
        "email STRING NOT NULL",
        "roles STRING"                     # multivalor separado por vírgula
    ]
}

def _sync_schema_tables(cursor, schema_dict, schema_label):
    """Utility: CREATE IF NOT EXISTS + ADD COLUMN sync for a given schema dict."""
    for table_name, columns in schema_dict.items():
        print(f"  [{schema_label}] Ensuring {table_name}...")
        try:
            cols_sql = ",\n                    ".join(columns)
            create_sql = f"CREATE TABLE IF NOT EXISTS {table_name} (\n                    {cols_sql}\n                )"
            cursor.execute(create_sql)

            try:
                cursor.execute(f"DESCRIBE {table_name}")
                existing_cols = {row.col_name.lower() for row in cursor.fetchall()}

                for col_def in columns:
                    if col_def.upper().startswith(("PRIMARY KEY", "FOREIGN KEY")):
                        continue

                    parts = col_def.split(maxsplit=1)
                    col_name = parts[0]

                    if col_name.lower() not in existing_cols:
                        clean_type = parts[1]
                        clean_type = re.sub(r'(?i)GENERATED\s+BY\s+DEFAULT\s+AS\s+IDENTITY', '', clean_type)
                        clean_type = re.sub(r'(?i)PRIMARY\s+KEY', '', clean_type)
                        clean_type = re.sub(r'(?i)NOT\s+NULL', '', clean_type)
                        clean_type = clean_type.strip()

                        try:
                            alter_sql = f"ALTER TABLE {table_name} ADD COLUMN {col_name} {clean_type}"
                            cursor.execute(alter_sql)
                            print(f"    Added column {col_name} to {table_name}")
                        except Exception as e:
                            print(f"    Failed to add column {col_name} to {table_name}: {e}")
            except Exception as e:
                print(f"  Could not describe and sync columns for {table_name}: {e}")
        except Exception as e:
            print(f"  Error executing CREATE TABLE or processing {table_name}: {e}")


def update_schema():
    conn = get_db_connection()
    try:
        with conn.cursor() as cursor:
            # 1. Process legacy renamed/deleted objects and column dropping
            # Note: To rename or drop columns in Delta, we must enable columnMapping.mode = 'name'
            migrations = [
                ("ALTER TABLE cri_cra_dev.crm.structuring_operation_series RENAME TO cri_cra_dev.crm.operation_series", "Rename series table"),
                ("ALTER TABLE cri_cra_dev.crm.structuring_operation_stages RENAME TO cri_cra_dev.crm.operation_stages", "Rename stages table"),
                ("DROP TABLE IF EXISTS cri_cra_dev.crm.structuring_operations", "Drop struct_operations"),
                
                # Enable Column Mapping to drop legacy columns
                ("ALTER TABLE cri_cra_dev.crm.operations SET TBLPROPERTIES ('delta.columnMapping.mode' = 'name', 'delta.minReaderVersion' = '2', 'delta.minWriterVersion' = '5')", "Enable column mapping on operations"),
                ("ALTER TABLE cri_cra_dev.crm.operation_series SET TBLPROPERTIES ('delta.columnMapping.mode' = 'name', 'delta.minReaderVersion' = '2', 'delta.minWriterVersion' = '5')", "Enable column mapping on operation_series"),
                ("ALTER TABLE cri_cra_dev.crm.operation_stages SET TBLPROPERTIES ('delta.columnMapping.mode' = 'name', 'delta.minReaderVersion' = '2', 'delta.minWriterVersion' = '5')", "Enable column mapping on operation_stages"),
                ("ALTER TABLE cri_cra_dev.crm.events SET TBLPROPERTIES ('delta.columnMapping.mode' = 'name', 'delta.minReaderVersion' = '2', 'delta.minWriterVersion' = '5')", "Enable column mapping on events"),
                ("ALTER TABLE cri_cra_dev.crm.task_rules SET TBLPROPERTIES ('delta.columnMapping.mode' = 'name', 'delta.minReaderVersion' = '2', 'delta.minWriterVersion' = '5')", "Enable column mapping on task_rules"),
                
                # Drop legacy columns (zombie columns that blocked mock_data.sql)
                ("ALTER TABLE cri_cra_dev.crm.operations DROP COLUMN rating_group", "Drop rating_group from operations"),
                ("ALTER TABLE cri_cra_dev.crm.operation_series DROP COLUMN structuring_operation_id", "Drop zombie col in series"),
                ("ALTER TABLE cri_cra_dev.crm.operation_stages DROP COLUMN structuring_operation_id", "Drop zombie col in stages"),
                ("ALTER TABLE cri_cra_dev.crm.events DROP COLUMN structuring_operation_stage_id", "Drop zombie col in events"),
                ("ALTER TABLE cri_cra_dev.crm.task_rules DROP COLUMN structuring_operation_stage_id", "Drop zombie col in task_rules")
            ]
            for sql, desc in migrations:
                try:
                    cursor.execute(sql)
                    print(f"Migration applied: {desc}")
                except Exception as e:
                    # Ignore if the rename/drop was already done or table missing
                    # print(f"Migration skipped: {desc} (Error: {e})") # Un-comment to trace
                    pass

            # 2. Re-create and Sync Columns for CRM schema
            _sync_schema_tables(cursor, SCHEMA, "crm")

            # 3. Create comite schema and sync Comitê tables
            try:
                cursor.execute("CREATE SCHEMA IF NOT EXISTS cri_cra_dev.comite")
                print("Schema cri_cra_dev.comite ensured.")
            except Exception as e:
                print(f"Schema cri_cra_dev.comite already exists or error: {e}")

            _sync_schema_tables(cursor, COMITE_SCHEMA, "comite")

            # 4. Post-sync adjustments (dropping NOT NULL constraints from old mandatory fields)
            nullable_cols = ['operation_type', 'maturity_date', 'responsible_analyst', 'review_frequency', 
                             'call_frequency', 'df_frequency', 'rating_operation', 'rating_group', 'watchlist']
            for col in nullable_cols:
                try:
                    cursor.execute(f"ALTER TABLE cri_cra_dev.crm.operations ALTER COLUMN {col} DROP NOT NULL")
                except Exception:
                    pass
            
            # Remove NOT NULL constraints from operation_id in entities that can be attached to a master_group instead
            try:
                cursor.execute("ALTER TABLE cri_cra_dev.crm.events ALTER COLUMN operation_id DROP NOT NULL")
                cursor.execute("ALTER TABLE cri_cra_dev.crm.operation_risks ALTER COLUMN operation_id DROP NOT NULL")
                cursor.execute("ALTER TABLE cri_cra_dev.crm.rating_history ALTER COLUMN operation_id DROP NOT NULL")
            except Exception as e:
                pass

            # Seed Patch notes
            cursor.execute("SELECT COUNT(*) as count FROM cri_cra_dev.crm.patch_notes")
            if cursor.fetchone().count == 0:
                print("Adding initial patch notes...")
                initial_changes = json.dumps(["Implementação inicial", "Gestão de operações unificada"])
                cursor.execute("""
                    INSERT INTO cri_cra_dev.crm.patch_notes (version, date, title, description, changes)
                    VALUES (?, ?, ?, ?, ?)
                """, ("1.0.0", datetime.now(), "Lançamento Inicial", "Primeira versão estável do sistema CRM.", initial_changes))

            conn.commit()
            print("Database schema updated successfully.")
    except Exception as e:
        print(f"Error updating schema: {e}")
    finally:
        conn.close()

if __name__ == "__main__":
    update_schema()
