import sqlite3
import re
import os

class GenericRow:
    def __init__(self, d):
        self.__dict__.update(d)
        
    def __getitem__(self, key):
        return self.__dict__.get(key)
        
    def get(self, key, default=None):
        return self.__dict__.get(key, default)

class DatabricksToSqliteMockCursor:
    def __init__(self, cursor):
        self.cursor = cursor
        self.description = None
        
    def execute(self, query, params=()):
        # Remove Databricks specific schema prefixes
        query = query.replace("cri_cra_dev.crm.", "")
        
        # Databricks allows string casts like CAST(id AS STRING). SqLite uses CAST(id AS TEXT)
        query = re.sub(r'CAST\(([^ ]+)\s+AS\s+STRING\)', r'CAST(\1 AS TEXT)', query, flags=re.IGNORECASE)
        
        self.cursor.execute(query, params)
        self.description = self.cursor.description
        return self
        
    def fetchone(self):
        row = self.cursor.fetchone()
        if not row:
            return None
        d = {desc[0]: val for desc, val in zip(self.description, row)}
        return GenericRow(d)
        
    def fetchall(self):
        rows = self.cursor.fetchall()
        res = []
        for row in rows:
            d = {desc[0]: val for desc, val in zip(self.description, row)}
            res.append(GenericRow(d))
        return res

class MockDatabricksConnection:
    def __init__(self, memory_conn):
        self.conn = memory_conn
        
    def cursor(self):
        # Return a context manager for the cursor
        class CursorContextManager:
            def __init__(self, c):
                self.c = DatabricksToSqliteMockCursor(c)
                
            def __enter__(self):
                return self.c
                
            def __exit__(self, exc_type, exc_val, exc_tb):
                pass
                
        return CursorContextManager(self.conn.cursor())
        
    def commit(self):
        self.conn.commit()
        
    def close(self):
        # We don't close the memory connection between requests so state persists during the test
        pass

def init_mock_db():
    schema_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'sql_schema.sql')
    with open(schema_path, 'r', encoding='utf-8') as f:
        sql = f.read()

    # Remove schema databricks syntax
    sql = re.sub(r'CREATE SCHEMA IF NOT EXISTS [A-Za-z0-9_.]+;', '', sql)
    sql = re.sub(r'USE [A-Za-z0-9_.]+;', '', sql)
    sql = sql.replace('cri_cra_dev.crm.', '')

    # Convert column types and identity definitions
    sql = re.sub(r'(id\s+)BIGINT GENERATED BY DEFAULT AS IDENTITY', r'\1INTEGER', sql)
    sql = sql.replace('BIGINT', 'INTEGER')
    sql = sql.replace('STRING', 'TEXT')
    sql = sql.replace('TIMESTAMP', 'TEXT')
    sql = sql.replace('BOOLEAN', 'INTEGER')

    # Remove COMMENT clauses using regex
    sql = re.sub(r"COMMENT\s+'[^']*'", "", sql)

    conn = sqlite3.connect(':memory:', check_same_thread=False)
    c = conn.cursor()
    # Need to execute statement by statement due to SQLite executescript limitations, but executescript works for pure DDL
    try:
        c.executescript(sql)
    except Exception as e:
        print("MOCK DB SCHEMA ERROR:", e)
        raise e
        
    return MockDatabricksConnection(conn)

